// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gekka.VisualStudio.Extension.CoverageTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMergeCoverageCommandPackageString = "58c63a85-6ae1-43b6-b669-ba7ff3d8dc01";
        public const string guidMergeCoverageCommandPackageCmdSetString = "f6639dc1-9c34-4303-852c-2113487a7c7b";
        public const string guidImagesString = "83bf7597-f2c4-46f7-b781-873b1afe7786";
        public const string guidVSMenuTestToolsString = "1e198c22-5980-4e7e-92f3-f73168d1fb63";
        public static Guid guidMergeCoverageCommandPackage = new Guid(guidMergeCoverageCommandPackageString);
        public static Guid guidMergeCoverageCommandPackageCmdSet = new Guid(guidMergeCoverageCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
        public static Guid guidVSMenuTestTools = new Guid(guidVSMenuTestToolsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MergeCoverageCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int IDM_VS_MENU_TEST = 0x0001;
    }
}
